/*
 * JS for page2 generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '2eb0f177-3285-4aa7-837a-004b7fe60898';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Appery.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Appery.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "page3",
    "location": "page3.html"
}, {
    "name": "page2",
    "location": "page2.html"
}];

page2_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobiletextarea_6': 'page2_mobiletextarea_6',
        'mobileimage_4': 'page2_mobileimage_4',
        'page3': 'page2_page3',
        'mobilelabel_3': 'page2_mobilelabel_3'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'page2';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    page2_beforeshow = function() {
        Appery.CurrentScreen = "page2";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_169E_onLoad = page2_onLoad = function() {
        screen_169E_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        page2_deviceEvents();
        page2_windowEvents();
        screen_169E_elementsEvents();
    }

    // screen window events
    screen_169E_windowEvents = page2_windowEvents = function() {

        $('#page2').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });

    }

    // device events
    page2_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_169E_elementsExtraJS = page2_elementsExtraJS = function() {
        // screen (page2) extra code

    }

    // screen elements handler
    screen_169E_elementsEvents = page2_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#page2_mobilecontainer1 [name="page3"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('page3', {
                        transition: 'slideup',
                        reverse: false
                    });

                }
            },
        });

    }

    $("#page2").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        page2_beforeshow();
    });

    if (runBeforeShow) {
        page2_beforeshow();
    } else {
        page2_onLoad();
    }

}

$("#page2").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    page2_js();
});