/*
 * JS for page3 generated by Appery.io
 *
 */

Appery.getProjectGUID = function() {
    return '2eb0f177-3285-4aa7-837a-004b7fe60898';
}

function navigateTo(outcome, useAjax) {
    Appery.navigateTo(outcome, useAjax);
}

function adjustContentHeight() {
    Appery.adjustContentHeight();
}

function adjustContentHeightWithPadding() {
    Appery.adjustContentHeightWithPadding();
}

function setDetailContent(pageUrl) {
    Appery.setDetailContent(pageUrl);
}

Appery.AppPages = [{
    "name": "startScreen",
    "location": "startScreen.html"
}, {
    "name": "page3",
    "location": "page3.html"
}, {
    "name": "page2",
    "location": "page2.html"
}];

page3_js = function(runBeforeShow) { /* Object & array with components "name-to-id" mapping */
    var n2id_buf = {
        'mobiletextarea_6': 'page3_mobiletextarea_6',
        'mobilebutton_6': 'page3_mobilebutton_6',
        'page2': 'page3_page2',
        'mobileimage_4': 'page3_mobileimage_4',
        'mobilelabel_3': 'page3_mobilelabel_3'
    };

    if ("n2id" in window && window.n2id !== undefined) {
        $.extend(n2id, n2id_buf);
    } else {
        window.n2id = n2id_buf;
    }

    if (navigator.userAgent.indexOf("IEMobile") != -1) {
        //Fixing issue https://github.com/jquery/jquery-mobile/issues/5424 on Windows Phone
        $("div[data-role=page] div[data-role=footer]").css("bottom", "-36px");
    }

    if (Appery.getTargetPlatform == "I") {
        $.each(window.n2id, function(name, id) {
            var elApperyRole = $("#" + id).attr("data-role");
            if (elApperyRole != "appery_label" && elApperyRole != "appery_link") {
                var appleDataSelector = "#" + id + "[x-apple-data-detectors], #" + id + " [x-apple-data-detectors]";
                $(appleDataSelector).attr("x-apple-data-detectors", "false");
            }
        });
    }

    Appery.CurrentScreen = 'page3';

    /*
     * Nonvisual components
     */
    var datasources = [];

    /*
     * Events and handlers
     */

    // Before Show
    page3_beforeshow = function() {
        Appery.CurrentScreen = "page3";
        for (var idx = 0; idx < datasources.length; idx++) {
            datasources[idx].__setupDisplay();
        }
    }

    // On Load
    screen_A74F_onLoad = page3_onLoad = function() {
        screen_A74F_elementsExtraJS();

        // TODO fire device events only if necessary (with JS logic)
        page3_deviceEvents();
        page3_windowEvents();
        screen_A74F_elementsEvents();
    }

    // screen window events
    screen_A74F_windowEvents = page3_windowEvents = function() {

        $('#page3').bind('pageshow orientationchange', function() {
            adjustContentHeightWithPadding();
        });

    }

    // device events
    page3_deviceEvents = function() {

        document.addEventListener("deviceready", function() {

        });
    }

    // screen elements extra js
    screen_A74F_elementsExtraJS = page3_elementsExtraJS = function() {
        // screen (page3) extra code

    }

    // screen elements handler
    screen_A74F_elementsEvents = page3_elementsEvents = function() {

        $("a :input,a a,a fieldset label").live({
            click: function(event) {
                event.stopPropagation();
            }
        });

        $('#page3_mobilecontainer1 [name="mobilebutton_6"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('page3', {
                        transition: 'slideup',
                        reverse: false
                    });
                    Appery.navigateTo('startScreen', {
                        transition: 'slidedown',
                        reverse: false
                    });

                }
            },
        });
        $('#page3_mobilecontainer1 [name="page2"]').die().live({
            click: function() {
                if (!$(this).attr('disabled')) {
                    Appery.navigateTo('page2', {
                        transition: 'slideup',
                        reverse: false
                    });

                }
            },
        });
        $('#page3_mobilecontainer1 [name="mobileimage_4"]').die().live({
            tap: function() {
                setAttribute_('page3', 'background-color', '#666');
                $('[id="page3"]').refresh();
            },
        });

    }

    $("#page3").die("pagebeforeshow").live("pagebeforeshow", function(event, ui) {
        page3_beforeshow();
    });

    if (runBeforeShow) {
        page3_beforeshow();
    } else {
        page3_onLoad();
    }

}

$("#page3").die("pageinit").live("pageinit", function(event, ui) {
    Appery.processSelectMenu($(this));
    page3_js();
});